services:
  bitcoind:
    container_name: knots-regtest
    image: bitcoinknots/bitcoin:latest
    command: -regtest=1 -server=1 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcuser=mempool -rpcpassword=mempool -txindex=1 -printtoconsole
    volumes:
      - ./data/regtest/bitcoin-data:/home/bitcoin/.bitcoin
    ports:
      - "18443:18443"
    networks:
      - bitcoin-net

networks:
  bitcoin-net:
    driver: bridge
